### ISSUE TITLE
[bug] Housekeeper sees both production path while in Stage

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/housekeeper#50] opened 2019-11-18 13:47 UTC
```
hasta /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06 Conda env: base Git repo: None Git branch: None
$ us
```
**112039** and **112040** still give prod path even though it is stage environment:
```
hasta /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06 Conda env: S_main Git repo: None Git branch: None
$housekeeper get calmcougar -V
75605 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_config.yaml | mip-config
75606 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_qc_sample_info.yaml | sampleinfo
75607 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar.fam | pedigree
75608 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/mip_2018-06-06T20:16:09.log | mip-log
75609 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_qc_metrics.yaml | qcmetrics
75610 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_BOTH.bcf | snv-gbcf
75611 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_BOTH.bcf.csi | snv-gbcf-index
75612 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_vrecal_comb_BOTH.bcf | snv-bcf
75613 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_vrecal_comb_BOTH.bcf.csi | snv-bcf-index
75614 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_SV.bcf | sv-bcf
75615 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_SV.bcf.csi | sv-bcf-index
75616 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar.ped_check.csv | peddy, ped-check
75617 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar.peddy.ped | peddy, ped
75618 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar.sex_check.csv | peddy, sex-check
75619 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_vrecal_comb_rhocall_vt_vep_parsed_snpeff_ranked_BOTH.selected.vcf.gz | vcf-snv-clinical
75620 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_vrecal_comb_rhocall_vt_vep_parsed_snpeff_ranked_BOTH.selected.vcf.gz.tbi | vcf-snv-clinical-index
75621 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_vrecal_comb_rhocall_vt_vep_parsed_snpeff_ranked_BOTH.vcf.gz | vcf-snv-research
75622 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_vrecal_comb_rhocall_vt_vep_parsed_snpeff_ranked_BOTH.vcf.gz.tbi | vcf-snv-research-index
75623 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_vep_parsed_ranked_SV.selected.vcf.gz | vcf-sv-clinical
75624 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_vep_parsed_ranked_SV.selected.vcf.gz.tbi | vcf-sv-clinical-index
75625 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz | vcf-sv-research
75626 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz.tbi | vcf-sv-research-index
75627 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/ACC4557A1_lanes_4444_sorted_md_brecal_coverage.bed | coverage, ACC4557A1
112039 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_vep_parsed_ranked_SV_bioit197.vcf.gz | bioit#197
112040 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_vep_parsed_ranked_SV_bioit197.selected.vcf.gz | bioit#197
147872 | /home/proj/stage/housekeeper-bundles/calmcougar/2018-06-06/delivery-report.html | delivery-report
```
Now if we down, and then up:

```
hasta /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06 Conda env: S_main Git repo: None Git branch: None
$down

hasta /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06 Conda env: base Git repo: None Git branch: None
$up

hasta /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06 Conda env: P_main Git repo: None Git branch: None
$housekeeper get calmcougar -V
75605 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_config.yaml | mip-config
75606 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_qc_sample_info.yaml | sampleinfo
75607 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar.fam | pedigree
75608 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/mip_2018-06-06T20:16:09.log | mip-log
75609 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_qc_metrics.yaml | qcmetrics
75610 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_BOTH.bcf | snv-gbcf
75611 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_BOTH.bcf.csi | snv-gbcf-index
75612 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_vrecal_comb_BOTH.bcf | snv-bcf
75613 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_vrecal_comb_BOTH.bcf.csi | snv-bcf-index
75614 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_SV.bcf | sv-bcf
75615 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_SV.bcf.csi | sv-bcf-index
75616 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar.ped_check.csv | peddy, ped-check
75617 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar.peddy.ped | peddy, ped
75618 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar.sex_check.csv | peddy, sex-check
75619 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_vrecal_comb_rhocall_vt_vep_parsed_snpeff_ranked_BOTH.selected.vcf.gz | vcf-snv-clinical
75620 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_vrecal_comb_rhocall_vt_vep_parsed_snpeff_ranked_BOTH.selected.vcf.gz.tbi | vcf-snv-clinical-index
75621 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_vrecal_comb_rhocall_vt_vep_parsed_snpeff_ranked_BOTH.vcf.gz | vcf-snv-research
75622 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_haptc_vrecal_comb_rhocall_vt_vep_parsed_snpeff_ranked_BOTH.vcf.gz.tbi | vcf-snv-research-index
75623 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_vep_parsed_ranked_SV.selected.vcf.gz | vcf-sv-clinical
75624 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_vep_parsed_ranked_SV.selected.vcf.gz.tbi | vcf-sv-clinical-index
75625 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz | vcf-sv-research
75626 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_vep_parsed_ranked_SV.vcf.gz.tbi | vcf-sv-research-index
75627 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/ACC4557A1_lanes_4444_sorted_md_brecal_coverage.bed | coverage, ACC4557A1
112039 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_vep_parsed_ranked_SV_bioit197.vcf.gz | bioit#197
112040 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/calmcougar_sorted_md_brecal_comb_vep_parsed_ranked_SV_bioit197.selected.vcf.gz | bioit#197
147872 | /home/proj/production/housekeeper-bundles/calmcougar/2018-06-06/delivery-report.html | delivery-report
```

Tested another sample in stage, and it didn't show production path:
case: `worthywalrus` (not pasting the output, it is too much text)

**Comment by hassanfa** [comment] 2019-11-18 13:47
I am not sure implications or severity of this bug, but storing samples in `stage` might lead to altering `production` as well. Can someone please investigate this and find the cause?

**Comment by hassanfa** [comment] 2019-11-18 13:49
@henrikstranneheim @emiliaol Unfortunately I won't be able to look into this for the time being, is this something worthy of CG project-board?

**Comment by emiliaol** [comment] 2019-11-18 14:12
I don't think this is a bug. I think the case is just available in both prod and stage as we often copy the prod db to stage.

**Comment by ingkebil** [comment] 2019-11-18 14:27
In a sense, this is the intended behaviour. Both 112039 and 112040 have been added with their fully qualified path. When that happens the base path to the housekeeper store is not prepended or changed.

So, the idea as to why we are allowing this was that we have two kinds of files we are storing in housekeeper: permanent and volatile ones.
The permanent ones are
- stored in the housekeeper store
- stored in a bundle
- are mainly used to track result files

The volatile ones
- can be anywhere on the file system
- don't have to exist
- are mainly used to track fastq files

I'll close this until we decide to alter the behaviour. Thanks for reporting!

**Closed by ingkebil** 2019-11-18 14:27 UTC
